[package]
name = "positioning-offline"
version = "0.1.0"
edition = "2024"

[dependencies]
"positioning" = {path = "../positioning"}

anyhow = { version = "1.0.95" }
log = { version = "0.4", default-features = false }
crossbeam-channel = "0.5.14"
