[package]
name = "positioning-offline"
version = "0.1.0"
edition = "2024"

[dependencies]
"positioning" = { path = "../positioning" }

log = { workspace = true }
crossbeam-channel = { workspace = true }
