[package]
name = "esp32c3-offline"
version = "0.1.0"
authors = ["Raffael Schmid <raffael.schmid@cloudarchitects.ch>"]
edition = "2021"  # Must be specified here too


[[bin]]
name = "esp32c3-offline"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors


[dependencies]
positioning = { path = "../../positioning" }
positioning-offline = { path = "../../positioning-offline" }
connect = { path = "../../connect" }
beacons = { path = "../../beacons", features = ["HCI"] }


esp-idf-svc = { workspace = true }
esp-idf-hal = { workspace = true }

log = { workspace = true }
crossbeam-channel = { workspace = true }

[build-dependencies]
embuild = { version = "0.33.0", features = ["espidf"] }
