[package]
name = "positioning"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.5.14"
log = { version = "0.4", default-features = false }

