name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LOCATION_SERVICE_CLIENT_ID: ${{ secrets.LOCATION_SERVICE_CLIENT_ID }}
  LOCATION_SERVICE_ENDPOINT: ${{ secrets.LOCATION_SERVICE_ENDPOINT }}
  LOCATION_SERVICE_KEY: ${{ secrets.LOCATION_SERVICE_KEY }}
  WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
  WIFI_SSID: ${{ secrets.WIFI_SSID }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src rustfmt clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install ldproxy
        run: cargo install ldproxy
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
